### ISSUE TITLE
Typo in "README.md"

### ISSUE THREAD

**Issue by harper1011** [spikeekips/serf-python#3]
Hi,

From "README.md" file, there are typo of member variables.
"is_sucess" should be "is_success".

Br,
-Dapeng Jiao

>>> def _callback (response, ) :
...     if not response.is_sucess :
...         raise ValueError(response.error, )
...
...     print response.body

>>> _client.stream().add_callback(_callback, ).watch()
>>> # or
>>> _client.stream().add_callback(_callback, ).request(watch=True, )

**Comment by spikeekips** [comment]
Thanks, @harper1011. fixed 👍
